### ISSUE TITLE
Goal: use-releases doesn't processes imported POMs in dependencyManagement

### ISSUE THREAD

**Issue by akacme** [mojohaus/versions-maven-plugin#134]
The imported BOMs are not processed correctly by use-releases goal, the fix for #79 is not working either.
I suppose this is due to how maven resolves imported POMs - there is no separate dependency for such import, it's replaced by list of dependencies defined in the POM.

**Comment by akacme** [comment]
Pull Request created: https://github.com/mojohaus/versions-maven-plugin/pull/135

**Comment by khmarbaise** [comment]
Merged PR #135

**Comment by ajarmoniuk** [comment]
I wanted to check if the same issue occurs in other Mojo's since they don't have that fix applied. It turns out that they don't suffer from the issue. 

Further, when I removed the patch from UseReleasesMojo, `import`-scoped dependencies were still present in the collected dependency management dependencies, which means that they are now present out of the box and can be treated by the mojo. And the `import` dependencies get updated. 

Which means that the patch can be removed. I'll create integration tests (important since Maven is involved) before doing that.

**Comment by ajarmoniuk** [comment]
Same issue: #25, #308, #309, #346, #395

**Comment by ajarmoniuk** [comment]
So, this problem is typically resolved by using dependency management from raw model.
