### ISSUE TITLE
How to tell versions-maven plugin to act on non-child modules ?

### ISSUE THREAD

**Issue by TristanCP** [mojohaus/versions-maven-plugin#136]
It looks like the plugin works only when you launch it on a parent module, but if you have an aggregator module with no parent, all the modules version are left unchanged. Is there a way to change this behaviour (without using "find") ?

http://stackoverflow.com/questions/28154902/how-to-use-versions-maven-plugin-to-set-child-module-versions
http://stackoverflow.com/questions/42905244/how-to-tell-versions-maven-plugin-to-act-on-non-child-modules

**Comment by khmarbaise** [comment]
Seemed to be related #13

**Comment by khmarbaise** [comment]
If you like to set versions of a reactor which contains only aggregator modules you have to add supplemental options. By default the versions-maven-plugin assumes a reactor contains of modules which have the same version number.
```
mvn versions:set -DnewVersion=10.5.6 -DgroupId=* -DartifactId=* -DoldVersion=*
```
This will change also modules which are aggregator modules within a multi project structure. The `-DoldVersion=*` is important otherwise any module which has a different version than the parent you are starting from is not changed. 

So this looks not like a bug in versions-maven-plugin 2.4 anymore. (I have not checked for older releases). So I close the issue. If you have further details or an example project please don't hesitate to open a new issue with the full description...

**Comment by BearKid** [comment]
> If you like to set versions of a reactor which contains only aggregator modules you have to add supplemental options. By default the versions-maven-plugin assumes a reactor contains of modules which have the same version number.

**Is it possible to set different version numbers for these aggregator modules ?**

Below is my use case, assume that there is a dependency graph like [ A -> B  ] :
Firstly, I have to update project version of  ProjectA, push commit and deploy artifact A.
Then, I can update ProjectB.  such as the version of dependency-A and the project version of ProjectB.
ProjectA and B have different version number.

I care the build order, it seems not possible (or easy)  to retrieve the reactor build order information of `aggregate`, I have no idea how to write my own sh script to iterate lots of modules in the correct build order.
