### ISSUE TITLE
processDependencies omits dependencies inherited from parent pom 

### ISSUE THREAD

**Issue by ggkochanski** [mojohaus/versions-maven-plugin#178]
When we have working project on which goal versions:update-properties is executed:
```
    <project>
        <parent>
           <artifactId>my-parent</artifactId>
        </parent>
        <properties>
              <my.version>1.1</my.version>
        </properties>
    </project>
```
and its parent:
 ```
   <project>
        <properties>
              <my.version>1.0</my.version>
        </properties>
        <dependencies>
             <dependency>
                  <artifactId>my-dependency</artifactId>
                  <version>${my.version}</version>
             </dependency>
        </dependencies>
    </project>

```
then property my.version is not updated:
    `Property ${my.version}: Leaving unchanged as 1.1`

Expected behavior: property my.version is updated:
    `Updated ${my.version} from 1.1 to 1.2`

Workaround: clone the dependency from parent to working project fixes the issue, my.version property is properly updated.

**Comment by khmarbaise** [comment]
First can you please make a full working example which shows the behaviour...and please add an output of your run...also which version of versions-maven-plugin do you use? And which version of Maven do you use? How exactly have you called ?

**Comment by ggkochanski** [comment]
Hi,
Please find attached zip with working example.
Script exmple/run.sh contains commands which reproduces the situation:
`(cd mywork && mvn versions:update-properties)`
outputs: `Property ${mylib.version}: Leaving unchanged as 1.1`.
After duplicating the dependency from the parent project:
`(cd mywork-workaround && mvn versions:update-properties)`
outputs: `Updated ${mylib.version} from 1.1 to 1.2`

The output of script run.sh is in attached zip under name example/out.txt.

Regards
Grzegorz
[example.zip](https://github.com/mojohaus/versions-maven-plugin/files/1125827/example.zip)

**Comment by Gerromie** [comment]
I have a similar project, but the properties for version definitions is kept in the parent pom. Example:

`    <properties>`
   `        <org.external.artifact.version>3.0.0</org.external.artifact.version>`
`      </properties>`

The child modules define the <dependencies> with a reference to ${org.external.artifact.version} as the required version. When running the goal versions:update-properties, no changes are made to the parent pom.xml or to any of the child pom.xml files.  

The instructions on https://www.mojohaus.org/versions-maven-plugin/examples/update-properties.html seem to imply that this is supported. However, my experience does not match the documentation.

**Comment by glianeric** [comment]
I have similar setups, but I don't want the child to make **any** updates to the parent's properties.  They are separated explicitly and controlled separately.
The parent contains the property, and sets it.  The child POM simply references that property and may have its own version properties that should be updated in it, but they are not the same as that in the parent.

Simple example:
parent contains a property:
-  <lib.a.version>1.0.0</lib.a.version>
-   an appropriate <dependency> for lib.a so that the versions plugin can manage this property.

child contains a property:
-  <lib.b.version>1.2.3</lib.b.version>  (but NOT a property for lib.a.version)
-   an appropriate <dependency> so that the versions plugin can manage it
-   a <dependency> on lib.a with version set to ${lib.a.version} inherited from the parent

Upon running update-properties on the child POM, I expect lib.a.version to NOT be changed in any way, and this is the way it works today.  I imagine that since the property is not listed in the POM, this will continue working as expected for me.
