### ISSUE TITLE
Release versions-maven-plugin 2.6

### ISSUE THREAD

**Issue by nhojpatrick** [mojohaus/versions-maven-plugin#269]
Is 2.6 ready to be release?
e.g. I'm after the fixes that have been done to correctly support maven-enforcer-plugin

**Comment by nhojpatrick** [comment]
@alexmonthy unable to use SNAPSHOT due to repo manager won't download them. Have checked on 2.6-SNAPSHOT works but can't use it at work

**Comment by giacgbj** [comment]
I've tried this snapshot and I found out that the only way to obtain a list of the upgradable plugins is to remove them from ~/.m2/repository/!
The command I use is:
`mvn org.codehaus.mojo:versions-maven-plugin:2.6-SNAPSHOT:display-plugin-updates`

What's happening?

**Comment by yoosiba** [comment]
last release is year old, and does not contain some fixes like #48
I also look forward to the release.

**Comment by dannil** [comment]
@giacgbj I have recently run into this problem on my Windows machine, where I get different lists of upgradeable plugins depending on if I run ` mvn org.codehaus.mojo:versions-maven-plugin:2.6-SNAPSHOT:display-plugin-updates` in my Linux subsystem or from the command prompt, since they have different repositories.  Have you been able to reproduce the problem? I might take a look at the problem in the coming weeks if I can narrow down what the actual problem is. Feel free to create an issue in the meantime.

**Comment by dannil** [comment]
@giacgbj The behavior is the result of the plugin reading the cached XML-files for the version data, instead of explicitly updating all the repositories every time (which would take up alot of bandwidth). Running Maven with the -U flag forces an update of the artifacts and the plugin works as expected.

**Comment by ST-DDT** [comment]
Which tasks have to be completed before the next release? Or is there something like a release window during which any scheduled releases take place?

**Comment by tzok** [comment]
+1 I also vote for a new version release.

**Comment by mikeobr** [comment]
Who has permissions to do a release?

**Comment by dannil** [comment]
@mikeobr checking the release history it seems like @khmarbaise and @olamy has (at least some) permissions.

**Comment by khmarbaise** [comment]
Hi, I have started the release process cause there is some need of an update of the plugin....

**Comment by khmarbaise** [comment]
I've started the VOTE process https://groups.google.com/forum/#!topic/mojohaus-dev/WUErj-rMhHg
please VOTE for it....

**Comment by khmarbaise** [comment]
Release done.

**Comment by PascalSchumacher** [comment]
Thank you very much! :+1:
