### ISSUE TITLE
Javadoc warning and errors

### ISSUE THREAD

**Issue by qualitesys** [mojohaus/versions-maven-plugin#327]

**Comment by qualitesys** [comment]
mvn site with maven-javadoc-plugin:2.10.4 still alert on doc errors

**Comment by slachiewicz** [comment]
Or welcome

**Comment by qualitesys** [comment]
Could you explain please ?

**Comment by slawekjaranowski** [comment]
@zaza thanks for info,  there was added many javadocs last time.

**Comment by ajarmoniuk** [comment]
No errors, but plenty of warnings. I suggest that folks create a javadoc if they change/update a method. Good idea? @sultan 

Can we reopen this and keep this item open? I've been working on this.

Or do we want to maintain that "code documents itself"? I think it doesn't as it's not always clear. Also, the "segment" selector sometimes indicates the last unchanged segment, otherwise the first segment that *can* change, so it must always be *clearly* documented. That's only one of the issues.

**Comment by sultan** [comment]
The code changed a lot. It would be ok to update the Java doc with each pr instead of Big Bang. I'll be Keeping that in mind
