### ISSUE TITLE
Missing use-releases for properties

### ISSUE THREAD

**Issue by ivanrododendro** [mojohaus/versions-maven-plugin#336]
Hi, 
it looks like it's not possible to apply use-releases to property versions

For example, when a version is declared like this : 
`<framework.version>0.1.17-SNAPSHOT</aas-framework.version>`

It's simply ignored by `versions:use-releases` because it does not process the properties and it's ignored by `versions:update-properties` because it ignores snapshots.

Am I missing something ?

**Comment by Stratehm** [comment]
Hi,

We have exactly the same need. May it be possible to add a configuration property `autoLinkItems` like in the `versions:update-properties` goal ?

**Comment by bfrisoni** [comment]
This would definitely be a great enhancement. Any idea when this might be released?

**Comment by cezar-tech** [comment]
> This would definitely be a great enhancement for versions:use-releases. Any idea when this might be released?
> 
> FYI. In the mean time, I am using something like below to achieve a similar behavior.
> 
> `mvn versions:update-properties -DallowIncrementalUpdates=false -DallowMajorUpdates=false -DallowMinorUpdates=false -Dincludes=groupId:artifactId:type:classifier:version`

Hey would you care to explain why what you are doing is a workaround for this problem ?
I'm experiencing the same thing here.

**Comment by bfrisoni** [comment]
> > This would definitely be a great enhancement for versions:use-releases. Any idea when this might be released?
> > FYI. In the mean time, I am using something like below to achieve a similar behavior.
> > `mvn versions:update-properties -DallowIncrementalUpdates=false -DallowMajorUpdates=false -DallowMinorUpdates=false -Dincludes=groupId:artifactId:type:classifier:version`
> 
> Hey would you care to explain why what you are doing is a workaround for this problem ?
> I'm experiencing the same thing here.

I am currently using version:update-properties to get around this. I disable major,minor,incremental version updates in addition, specify a include argument to only include the group id (internal framework group id) of the artifacts I wish to upgrade to release versions. The end result is the internal framework library version that is specified in a maven property will be upgraded to the release version if it exists. 

`mvn -B -e versions:update-properties -DallowIncrementalUpdates=false -DallowMajorUpdates=false -DallowMinorUpdates=false -DgenerateBackupPoms=false -Dincludes=${groupdId}::::`

**Comment by pjroth** [comment]
This is a feature of `versions:use-releases` I would like to use as well if it was available.

@bfrisoni your workaround works great for me.  Thanks!  Since your set of flags essentially limit the updates to ONLY impact SNAPSHOTs I don't even bother with the -Dincludes since for my use case I want all SNAPSHOTs to be converted to their release versions.  Thinking about it more, this seems like what I'd want `versions:use-releases` to do since that's what it does already for non-property defined versions.  Just to be clear, I'm using: 

`mvn` versions:update-properties -DallowIncrementalUpdates=false -DallowMajorUpdates=false -DallowMinorUpdates=false -DgenerateBackupPoms=false`
