### ISSUE TITLE
allow to specify a filter for update-properties allow snapshot

### ISSUE THREAD

**Issue by fredmorin** [mojohaus/versions-maven-plugin#462]
our team uses a feature branch strategy, we would like to use the update properties plugin to allow parameterization of a filter.

example of the functionality where it updates properties to the {feature-branch} snapshot.: 
0.1.0 -> 0.2.0-{feature-branch}-SNAPSHOT

one possible way to support such feature would be to add a parameter to UseNextSnapshotsMojo

```java
    /**
     * Whether to allow the incremental version number to be changed.
     *
     * @since 1.0-beta-1
     */
    @Parameter( property = "filterPattern", defaultValue = "" )
    private String filterPattern;

    // ------------------------------ FIELDS ------------------------------

```
then modify matchSnapshotRegex to include the filterPattern

```java
    /**
     * Pattern to match a snapshot version.
     */
    public final Pattern matchSnapshotRegex = Pattern.compile( "^(.+)-((SNAPSHOT)|(\\d{8}\\.\\d{6}-\\d+))$" );
```

https://github.com/mojohaus/versions-maven-plugin/blob/versions-maven-plugin-2.8.1/src/main/java/org/codehaus/mojo/versions/UseNextSnapshotsMojo.java#L83

I will create merge request if this solution appears acceptable.

Thanks for this great project 👍

**Comment by bmarwell** [comment]
Hi @fredmorin 

I am not sure I understand:

* What is the use case you want to follow when using "update Properties"?
* what is the current situation with this plugin? E.g. what happens if you execute it?
* What is the expected output?
* Now, if there are multiple feature branches, what would you expect the plugin to do?
* What is the proposed change to the Patterns you referenced?

Versions in Maven are (usually) x.y.z-SNAPSHOT, and everything which does not end in `-SNAPSHOT` is considered a release version. JBoss uses `x.y.z.FINAL`, you most just use `x.y.z`.
