### ISSUE TITLE
Allow setting a project's parent version to a dedicated one

### ISSUE THREAD

**Issue by odrotbohm** [mojohaus/versions-maven-plugin#610]
Currently, the `update-parent` goal cannot *downgrade* a project's parent version. The documentation lists a `parentVersion` parameter that kind of implies one could set the project's version to a dedicated one. However, the property only controls dependency resolution for the step of changing the version.

**Comment by bianjp** [comment]
I want this feature too.

How about adding a new property named `newVersion` which will be used as the parent version without resolution (works like `newVersion` in `versions:set` goal)? Or adding a new `versions:set-parent` goal?

**Comment by slawekjaranowski** [comment]
`newVersion` property will be ok 

TODO:
 - clarify documentation of `parentVersion` 
 - update examples - https://www.mojohaus.org/versions-maven-plugin/examples/update-parent.html

**Comment by ajarmoniuk** [comment]
I'll take it on my bandwagon.

**Comment by ajarmoniuk** [comment]
@odrotbohm @bianjp it is undocumented and probably a side effect of how available version resolution works, but it is in fact possible to downgrade a non-snapshot version to a specified version. In order to do so, just surround the version in square brackets, like so:

`[0.8.0]`

Then, the version will be *downgraded*. I think I'll add a couple a test documenting/verifying this plus maybe a new argument not to use the square brackets? @slawekjaranowski what do you think?

An explainer in the documentation is a must.

`parentVersion` is a hint to the available resulution system about the *lowest* version from which the sought version range should start -- or can be a version range, in which case the sought version range will be restricted by that version range. And that last possibility is what we're using here.

**Comment by bianjp** [comment]
> it is undocumented and probably a side effect of how available version resolution works, but it is in fact possible to downgrade a non-snapshot version to a specified version.

I know this works, even for snapshot versions. But it still goes through a resolution process and requires that the specified parentVersion already exists in maven repository.

I wish that a new argument could be added to bypass the resolution process.

**Comment by haj205** [comment]
It would really help to skip the resolution process and have a dedicated version updated. In my case, we have different release branches 22.03.100, 22.04.100 and the versions as 22.03.100-SNAPSHOT / 22.04.100-SNAPSHOT and I am not able to update parent versions on different branches with respective release versions.

**Comment by ajarmoniuk** [comment]
Then I think it would be better to reuse `parentVersion` here, but introduce a new parameter, say, `skipResolution`.

Why? Because `newVersion` exists elsewhere and it would be highly confusing if it had different meaning for `update-parent`.

**Comment by haj205** [comment]
That makes sense to me ..

**Comment by haj205** [comment]
> Then I think it would be better to reuse `parentVersion` here, but introduce a new parameter, say, `skipResolution`.
> 
> Why? Because `newVersion` exists elsewhere and it would be highly confusing if it had different semantics for `update-parent`.

This sounds good..

**Comment by ajarmoniuk** [comment]
Implementation done. The PR will be ready once the PR for the DependencyBuilder is merged in.
